require("nvim-treesitter").setup({
  ensure_installed = {
    "eex",
    "elixir",
    "erlang",
    "heex",
    "html",
    "javascript",
    "lua",
    "markdown",
    "markdown_inline",
    "ruby",
    "surface",
    "tsx",
    "typescript",
  },
  auto_install = true,
  highlight = { enable = true },
  indent = { enable = true },
})
