require("nvim-treesitter.configs").setup {
  ensure_installed = {
    "eex",
    "elixir",
    "erlang",
    "heex",
    "html",
    "javascript",
    "lua",
    "ruby",
    "surface",
    "tsx",
    "typescript",
  },
  sync_install = false,
  auto_install = true,
  ignore_install = {},
  highlight = {enable = true},
  indent = {enable = true},
}
